version: '3'
services:
  server:
    image: rancher/k3s:v1.24.4-k3s1
    command: server --disable-agent --tls-san 172.17.0.1
    environment:
      - K3S_CLUSTER_SECRET=somethingtotallyrandom
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ${TRAVIS_BUILD_DIR:-..}/scripts:/output
    ports:
      - 6443:6443

  node:
    image: rancher/k3s:v1.24.4-k3s1
    tmpfs:
      - /run
      - /var/run
    privileged: true
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=somethingtotallyrandom

  registry:
    image: registry:2
    ports:
      - 5000:5000
