services:
  server:
    image: rancher/k3s:v1.31.2-k3s1
    command: server --disable-agent --tls-san 172.17.0.1 --agent-token somethingtotallyrandom
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ../scripts:/output
    ports:
      - 6443:6443

  node:
    image: rancher/k3s:v1.31.2-k3s1
    command: agent --token somethingtotallyrandom --server https://server:6443
    privileged: true
    restart: always
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  registry:
    platform: linux/amd64
    image: registry:2
    ports:
      - 6500:5000
