name: "Build"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Build
        run: make build

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Run unit tests
        run: make test

  testacc:
    strategy:
      matrix:
        k3s_version:
          - v1.31.2-k3s1
          - v1.30.6-k3s1
          - v1.29.10-k3s1
          - v1.28.15-k3s1
          - v1.27.16-k3s1
          - v1.26.15-k3s1
          - v1.25.16-k3s4
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Start k3s
        run: make k3s-start
        env:
          K3S_VERSION: ${{ matrix.k3s_version }}
      - name: Run acceptance tests
        run: make testacc
      - name: Stop k3s
        run: make k3s-stop

  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Format check
        run: make fmtcheck

  vet:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - name: Set up GO 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Setup Environment
        run: make ci-build-setup
      - name: Run vet
        run: make vet
