name: Cache images for tests in GHCR

on:
  push:
    paths:
      - 'scripts/docker-compose.yaml'
      - '.github/workflows/docker.yml'

env:
  IMAGES: "rancher/k3s:v1.31.2-k3s1,registry:2"

jobs:
  cache-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Cache images
        run: |
          for image in ${IMAGES//,/ }; do
            new_image="ghcr.io/gavinbunney/terraform-provider-kubectl/testacc-$(echo $image | sed 's/\//-/')"
            echo "Caching $image as $new_image"
            docker pull $image
            docker tag $image $new_image
            docker push $new_image
          done
